### ISSUE TITLE
Date filter for bookings

### ISSUE THREAD

**Issue by johanneshochholzer** [isarwatt/klink-issues-public#16]
**Product**
Admin Frontend

**Describe the solution you'd like**
Filter Bookings in booking list by date
Sort by date (of the bookings to happen not when they were made).
e.g. Show all bookings for Gemeinschaftsraum from 1st October to 15th October

**Comment by benediktdertinger** [comment]
@johanneshochholzer is it sufficient for the MVP to only use these order options instead of input + range? For MVP this would add quite some complexity.

Additionally the filter will search resource title + booking code.
<img width="792" alt="Screenshot 2021-10-22 at 11 35 58" src="https://user-images.githubusercontent.com/6225675/138431517-e437a0e9-bf95-41a4-8f75-bb7d4a5fb23f.png">

**Comment by johanneshochholzer** [comment]
I'm fine with the filter options that are shown in the screenshot
