### ISSUE TITLE
Reset resource search location

### ISSUE THREAD

**Issue by johanneshochholzer** [isarwatt/klink-issues-public#31]
**Product**
Frontend

**Describe the bug**
You cannot empty the browse bar once something is set.

**To Reproduce**
1. open browse bar
2. choose a place, e.g. Cohaus Kloster Schlehdorf
3. You now would like to view everything availabe
4. you cannot reset the browse bar except by clicking on booking in the menu

**Expected behavior**
one should be able to reset the browse bar without picking another location / starting from the beginning.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/75273091/137199805-b1a46129-eeaa-4422-a2ce-f2a6f031c72d.png)

**Comment by benediktdertinger** [comment]
@johanneshochholzer i think what you are searching for here is an overview/intro page which is not yet built. I suggest that we keep it like we implemented it here. As soon as the location-based search is added, you can change the values to whatever you always want to have a specific result rather than >all germany< or something like that. And for the overview you would definitely use overview pages.

**Comment by johanneshochholzer** [comment]
I'm missing a button to empty the current search field.
This is necessary as we currently would like to display everything that is on the platform.
See on airbnb: (x) button
![grafik](https://user-images.githubusercontent.com/75273091/137759059-bc973cb8-57ac-4a0b-a695-7e0ae0b9b5c9.png)

**Comment by benediktdertinger** [comment]
@johanneshochholzer exactly, but if you click on the empty input button the search result is not reset. Instead it stays the same to be only changed if you input something else. That's why I recommend to follow this path and not alter the search but only reset the input value when clicking on the empty input button.

There are several reasons for not resetting the whole search in this case.

This is already implemented.
<img width="320" alt="Screenshot 2021-10-18 at 17 35 55" src="https://user-images.githubusercontent.com/6225675/137763537-92ef8eb3-ff8c-4800-bc49-cd8f80564d72.png">

**Comment by johanneshochholzer** [comment]
![grafik](https://user-images.githubusercontent.com/75273091/138321565-1cbd6549-e900-4715-94e7-eec9b87557a7.png)
Once something is selected, I cannot unselect it.
This is different with airbnb:
![grafik](https://user-images.githubusercontent.com/75273091/138321686-9a3c2fef-85c1-4a46-89c2-2f9235e1cc44.png)

The User Story is this:
I'm searching in Schlehdorf
![grafik](https://user-images.githubusercontent.com/75273091/138321565-1cbd6549-e900-4715-94e7-eec9b87557a7.png)
And then I would like to search without a special place filter
![grafik](https://user-images.githubusercontent.com/75273091/138321888-e37fd059-68b9-4393-bebb-ae1f2921a519.png)
This however just works by reloading the page. I would like to cancel the current selection (Cohaus Kloster Schlehdorf)

**Comment by benediktdertinger** [comment]
Covered in https://github.com/isarwatt/klink-issues/issues/157
