### ISSUE TITLE
Search for Quarter needs optimisation

### ISSUE THREAD

**Issue by johanneshochholzer** [isarwatt/klink-issues-public#36]
**Product**
Frontend

**Describe the bug**
The search for quarters leads to incoherent results

**To Reproduce**
1. No search results
![grafik](https://user-images.githubusercontent.com/75273091/137444967-bceb6050-f50f-415d-99da-3e98db473bd5.png)
Clicking on the quarter doesn't open the search results
- [x] Center map to quarter address.coordinates
- [x] Trigger search for coordinates
- [x] Update list + map pins accordingly
- [x] Add quarter title to search bar field

2. Label is sometimes wrong
![grafik](https://user-images.githubusercontent.com/75273091/137445192-704f8bdc-7fbb-4446-808b-2812e27ec8c3.png)
The quarter Schlehdorf is not in Munich, can that be location generated.
- [x] Use quarter.description for this label

3. Idea for new representation (more coherent for all places)
![grafik](https://user-images.githubusercontent.com/75273091/137445287-57079368-1740-4124-a7a2-773535c443f3.png)
Can we show everything in the same way?
So no headlines for Buchungsobjekte etc., but everything is showed with a label, e.g.
- Schlehdorf (Label Quartier)
- Cohaus Kloster Schlehdorf (Label Projekt)
- Besprechungsraum Schlehdorf (Label Ressource)
- [x] Already fixed

**Expected behavior**
Q, P, O and R show the same behaviour and share a similar representation in the places searchbar.

**Comment by david-ziegler** [comment]
About the second point: isn't it a bad idea to show the description here in the search results? The description can be really long (several hundred characters or more). Do we truncate it then? Isn't the existing label "Quartier in {city}" better here, since it might be a good information in what city that is?
About the third point: @benediktdertinger we didn't fix it the way Johannes described it above. He described that there should be no titles at all. Just search results, each with a label behind it.

But let's be reminded again that we are doing an MVP, where we shouldn't get lost in details, so maybe it's fine like it is implemented now?

**Comment by benediktdertinger** [comment]
> About the second point: isn't it a bad idea to show the description here in the search results? The description can be really long (several hundred characters or more). Do we truncate it then? Isn't the existing label "Quartier in {city}" better here, since it might be a good information in what city that is? About the third point: @benediktdertinger we didn't fix it the way Johannes described it above. He described that there should be no titles at all. Just search results, each with a label behind it.
> 
> But let's be reminded again that we are doing an MVP, where we shouldn't get lost in details, so maybe it's fine like it is implemented now?

We solve this via https://github.com/orgs/isarwatt/projects/3

**Comment by benediktdertinger** [comment]
@johanneshochholzer you can check and close it
